### ISSUE TITLE
Brief solution for GPA calculating.

### ISSUE THREAD

**Issue by lexuancuong** [phamtrongthang123/RamdomProj#1]
Just open your total GPA page and execute this code on your browser:

`var credit = document.querySelectorAll("td:nth-child(3)");
var subjects = document.querySelectorAll("td:nth-child(2)");
var grade = document.querySelectorAll("td:nth-child(6)");
var GPA_Credits = 0, Credits = 0;
for (var i = 1; i < credit.length; i++) {
    if (
        subjects[i].innerText.includes("Thể dục") ||
        subjects[i].innerText.includes("Anh văn") ||
        subjects[i].innerText.includes("Giáo dục") || Number(grade[i].innerText) < 5
    ) {
        continue;
    }
    GPA_Credits += Number(credit[i].innerText) * Number(grade[i].innerText);
    Credits += Number(credit[i].innerText);
}

console.log((GPA_Credits / Credits).toFixed(2))`

**Comment by lexuancuong** [comment]
Thank you so much @phamtrongthang123

**Comment by phamtrongthang123** [comment]
Thay vì mỗi lần vào f12 và run thì extension này chỉ cần click 1 lần là đủ.
